account/urls.py
from django.urls import path
from . import views

app_name = 'account'

urlpatterns = [
    path('account/register', views.UserRegisterationView.as_view(), name='register'),
    path('account/login', views.UserLoginView.as_view(), name='login'),
    path('account/logout', views.UserLogoutView.as_view(), name='logout'),
    path('account/profile/<int:user_id>', views.UserProfileView.as_view(), name='profile'),
    path('account/follow/<int:user_id>', views.UserFollowView.as_view(), name='follow'),
    path('account/unfollow/<int:user_id>', views.UserUnfollowView.as_view(), name='unfollow'),
    path('profile/edit/', views.ProfileEditView.as_view(), name='profile_edit'),

]

home/urls.py
from django.urls import path
from . import views

app_name = 'home'
urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),
    path('post_detail/<int:post_id>/<slug:post_slug>/', views.PostDetailView.as_view(), name='post_detail'),
    path('post_edit/<int:post_id>/', views.PostEditView.as_view(), name='post_edit'),
    path('post_delete/<int:post_id>/', views.PostDeleteView.as_view(), name='post_delete'),
    path('post_create/', views.PostCreateView.as_view(), name='post_create'),
    # path('reply/<int:post_id>/<int:comment_id>/', views.PostAddReplyView.as_view(), name='add_reply'),
    path('post/<int:post_id>/<slug:post_slug>/like/', views.LikePostView.as_view(), name='post_like'),


    ]

twitter/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('', include('account.urls'))
] 
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse

class Post(models.Model):
	user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='posts')
	body = models.TextField()
	slug = models.SlugField()
	title = models.CharField(max_length=100, null=True, blank=True)
	created = models.DateTimeField(auto_now_add=True)
	updated = models.DateTimeField(auto_now=True)

	class Meta:
		ordering = ['-created']

	def get_absolute_url(self):
		return reverse('home:post_detail', args=(self.id, self.slug))
	
	
	def total_likes(self):
		return self.like_set.count()
	
	def user_has_liked(self, user):
		return self.like_set.filter(user=user).exists()

	def __str__(self):
		return f'{self.slug} - {self.updated}'
	
class PostImage(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name="images")
    image = models.ImageField(upload_to="post_images/")
	

class Comment(models.Model):
	post = models.ForeignKey(Post, on_delete=models.CASCADE)
	user = models.ForeignKey(User, on_delete=models.CASCADE)
	body = models.TextField(max_length=400)
	reply = models.ForeignKey('self', on_delete=models.CASCADE, null=True, blank=True, related_name='rcomments')
	is_reply = models.BooleanField(default=False)
	created = models.DateTimeField(auto_now_add=True)

	def __str__(self):
		return f'{self.user} - {self.body[:30]}'
	
	
class Like(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    created = models.DateTimeField(auto_now_add=True)

    class Meta:
        unique_together = ('user', 'post')

    def __str__(self):
        return f'{self.user} likes {self.post}'

home/forms.py
from django import forms
from . models import Post, Comment

class PostCreateEditForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['title', 'body']


class CommentCreateReplyForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['body', 'reply']
    def __init__(self, *args, **kwargs):
        super(CommentCreateReplyForm, self).__init__(*args, **kwargs)
        self.fields['reply'].widget = forms.HiddenInput()  

        

home/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views import View
from . models import Post, PostImage, Comment, Like
from . forms import PostCreateEditForm, CommentCreateReplyForm
from django.forms import modelformset_factory, BaseModelFormSet
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.utils.text import slugify


class HomeView(View):
    def get(self, request):
        posts = Post.objects.all()
        return render(request,'home/home.html', {'posts':posts})


class PostDetailView(View):
    form_class_comment = CommentCreateReplyForm
    def get(self, request, post_id, post_slug):
        post = Post.objects.get(id=post_id, slug=post_slug)
        if self.request.user.is_authenticated:
            user_has_liked = Like.objects.filter(user=self.request.user, post=post).exists()
        else:
            user_has_liked = False

        comments = post.comment_set.all()
        comment_form = self.form_class_comment()
        return render(request, 'home/post_detail.html', {'post':post, 'comments':comments, 'comment_form':comment_form, 'user_has_liked':user_has_liked})
    
    def post(self, request, post_id, post_slug):
        comment_form = self.form_class_comment(request.POST)
        post = Post.objects.get(id=post_id, slug=post_slug)
        if comment_form.is_valid():
            new_comment_form = comment_form.save(commit=False)
            new_comment_form.post = post
            new_comment_form.user = request.user

            parent_comment = comment_form.cleaned_data['reply']
            if parent_comment:
                new_comment_form.is_reply = True

            new_comment_form.save()
            messages.success(request, 'comment add successfully', 'success')
            return redirect('home:post_detail', post_id=post.id, post_slug=post.slug)
        
        comments = post.comment_set.all()
        return render(request, 'post_detail.html', {
            'post': post,
            'comments': comments,
            'comment_form': comment_form
        })

class PostEditView(LoginRequiredMixin, View):
    form_class = PostCreateEditForm
    def get(self, request, post_id):
        post = Post.objects.get(id=post_id)
        post_form = self.form_class(instance=post)

        ImageFormSet = modelformset_factory(PostImage, fields=('image',), extra=2, can_delete=True)
        formset = ImageFormSet(queryset=post.images.all())


        return render(request, 'home/post_edit.html', {'form':post_form, 'formset': formset, 'post': post})
    
    def post(self, request, post_id):
        post = Post.objects.get(id=post_id)
        post_form = self.form_class(request.POST, instance=post)

        ImageFormSet = modelformset_factory(PostImage, fields=('image',), extra=2, can_delete=True)
        formset = ImageFormSet(request.POST, request.FILES, queryset=post.images.all())
        print(request.POST)
        print(request.FILES)


        

        if post_form.is_valid() and formset.is_valid():
            new_post = post_form.save(commit=False)
            new_post.user = request.user
            body = post_form.cleaned_data['body']
            new_post.slug = slugify(body[:10])

            new_post.save()

            # Handle images in the formset
            print(formset.cleaned_data)
            for form in formset:
                if form.cleaned_data:
                    print(form.cleaned_data)
                    print('pk', form.instance.id)
                    if form.cleaned_data.get('DELETE') and form.instance.pk:
                        print('delete')
                        form.instance.delete()
                    elif not form.cleaned_data.get('DELETE'):
                        print('not delete')
                        image = form.save(commit=False)
                        image.post = new_post
                        image.save()

            messages.success(request,'updated successfully!','success')
            return redirect('home:post_detail', post.id, post.slug)
        
        else:
            # Print errors to the console or log them for debugging
            print("Post form errors:", post_form.errors)
            print("Formset errors:", formset.errors)


        return render(request, 'home/post_edit.html', {'form': post_form, 'formset': formset, 'post': post})

class PostDeleteView(LoginRequiredMixin, View):
    def post(self, request, post_id):
        post = Post.objects.get(id=post_id)
        post.delete()
        messages.success(request, 'post deleted successfully!', 'success')
        return redirect('home:home')
    
    def get(self, request, post_id):
        post = Post.objects.get(id=post_id)
        return render(request, 'home/post_confirm_delete.html', {'post': post})
            

class PostCreateView(LoginRequiredMixin, View):
    form_class = PostCreateEditForm
    def get(self, request):
        form = self.form_class()
        ImageFormSet = modelformset_factory(PostImage, fields=('image',), extra=3)  
        formset = ImageFormSet(queryset=PostImage.objects.none())  
        return render(request, 'home/post_create.html',{'form':form, 'formset': formset})

    def post(self, request):
        form = self.form_class(request.POST, request.FILES)
        ImageFormSet = modelformset_factory(PostImage, fields=('image',), extra=3)
        formset = ImageFormSet(request.POST, request.FILES, queryset=PostImage.objects.none())
        if form.is_valid() and formset.is_valid():
            new_form = form.save(commit=False)
            new_form.user = request.user
            new_form.body = form.cleaned_data['body']
            new_form.slug = slugify(form.cleaned_data['body'][:10])
            new_form.save()
            # Save images from formset
            for form in formset:
                if form.cleaned_data:
                    image = form.save(commit=False)
                    image.post = new_form
                    image.save()


            messages.success(request, 'post created succssfully!', 'success')
            return redirect('home:post_detail', new_form.id, new_form.slug)
        return render(request, 'home/post_create.html', {'form':form, 'formset': formset})
    

class LikePostView(LoginRequiredMixin, View):
    def post(self, request, post_id, *args, **kwargs):
        post = get_object_or_404(Post, id=post_id)
        like, created = Like.objects.get_or_create(user=request.user, post=post)

        if not created:
            
            like.delete()

        return redirect('home:post_detail', post_id=post.id, post_slug=post.slug)

home/templates/home/home.html
{% extends 'base.html' %}

{% block title %}Home{% endblock %}

{% block content %}
<div class="container my-4">
    <h2 class="mb-4">Recent Posts</h2>

    <div class="d-flex justify-content-end mb-4">
        {% if user.is_authenticated %}
        <a href="{% url 'home:post_create' %}" class="btn btn-success">Create Post</a>
        {% endif %}
    </div>

    
    <div class="row">
        <!-- Loop through posts -->
        {% for post in posts %}
        <div class="col-12 mb-4">
            <div class="card h-100">
                <div class="card-body">
                    <h5 class="card-title">{{ post.title }}</h5>
                    <p class="card-text">
                        {{ post.body|truncatewords:20 }}  
                    </p>
                    <a href="{{ post.get_absolute_url }}" class="btn btn-primary">Read More</a>
                </div>
                <div class="card-footer text-muted">
                    Posted by  <a href="{% url 'account:profile' post.user.id %}"> {{ post.user }} </a> on {{ post.created|date:"F d, Y" }}
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js"></script>
{% endblock %}

home/templates/home/post_confirm_delete.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Delete Post</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet">
</head>
<body>
    <div class="container mt-5">
        <h2>Are you sure you want to delete this post?</h2>
        <p>{{ post.title }}</p>

        <form method="POST" action="{% url 'home:post_delete' post.id %}">
            {% csrf_token %}
            <button type="submit" class="btn btn-danger">Delete</button>
            <a href="{% url 'home:home' %}" class="btn btn-secondary">Cancel</a>
        </form>
    </div>
</body>
</html>

home/templates/home/post_create.html
{% extends 'base.html' %}

{% block title %}Create Post{% endblock %}

{% block content %}
<div class="container my-4">
    <h2>Create a New Post</h2>
    
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        
        <!-- Post Form Fields -->
        {{ form.as_p }}

        <!-- Image Formset Fields -->
        {{ formset.management_form }}
        <div class="form-group">
            <label>Upload Images:</label>
            {% for form in formset %}
                {{ form.image.label }} {{ form.image }}
            {% endfor %}
        </div>
        
        <button type="submit" class="btn btn-primary">Create Post</button>
    </form>
</div>
{% endblock %}

home/templates/home/post_detail.html
{% extends "base.html" %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Post Detail</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet">
</head>
<body>
    {% block content %}
    <div class="container my-4">
        <h2>{{ post.title }}</h2>
        <p>{{ post.body }}</p>
         <!-- Display post images -->
    <div class="post-images mb-4">
        {% for image in post.images.all %}
            <img src="{{ image.image.url }}" class="img-fluid mb-2" alt="Post Image">
        {% endfor %}
    </div>

        {% if request.user.id == post.user.id %}
        <div class="mt-4">
            <a href="{% url "home:post_edit" post.id %}" class="btn btn-warning">Edit Post</a>  <!-- Edit button -->
            <!-- Delete button with href -->
            <a href="{% url 'home:post_delete' post.id %}" class="btn btn-danger" 
               onclick="return confirm('Are you sure you want to delete this post?');">Delete Post</a>
            <a href="{% url "home:home" %}" class="btn btn-secondary">Back to Home</a>
        </div>
        {% endif %}
    </div>

    {% if request.user.is_authenticated %}
    <div class="post-likes">
        <p>{{ post.total_likes }} likes</p>
    
        <form action="{% url 'home:post_like' post.id post.slug %}" method="POST">
            {% csrf_token %}
            {% if user_has_liked %}
                <button type="submit" class="btn btn-danger">Unlike</button>
            {% else %}
                <button type="submit" class="btn btn-primary">Like</button>
            {% endif %}
        </form>
    </div>
    {% endif %}
    
<!-- Comments Section -->
<div class="comments-section mt-5">
    <h4>Comments</h4>

    {% if comments %}
        <ul class="list-group">
            {% for comment in comments %}
            {% if comment.is_reply is False %}
                <li class="list-group-item">
                    <strong>{{ comment.user.username }}:</strong> {{ comment.body }}
                    <small class="text-muted d-block">{{ comment.created }}</small>

                    {% if request.user.is_authenticated %}
                    <!-- Reply button -->
                    <a href="#" class="reply-btn" data-bs-toggle="collapse" data-bs-target="#replyForm{{ comment.id }}">Reply</a>

                    <!-- Reply Form (Collapsible) -->
                    <div class="collapse mt-3" id="replyForm{{ comment.id }}">
                        <form action="{% url 'home:post_detail' post.id post.slug %}" method="POST">
                            {% csrf_token %}
                            {{ comment_form.as_p }}
                            <!-- Hidden input to store parent comment ID -->
                            <input type="hidden" name="reply" value="{{ comment.id }}">
                            <button type="submit" class="btn btn-primary">Submit Reply</button>
                        </form>
                    </div>
                    {% endif %}
            {% endif %}
                    <!-- Show replies -->
                   {% if comment.is_reply is False  %}
                        <ul class="list-group mt-3">
                            {% for reply in comment.rcomments.all %}
                                <li class="list-group-item">
                                
                                    <strong>{{ reply.user.username }}:</strong> {{ reply.body }}
                                    <small class="text-muted d-block">{{ reply.created }}</small>
                                </li>
                            {% endfor %}
                        </ul>
                    {% endif %}
                </li>
            {% endfor %}
        </ul>
    {% else %}
        <p>No comments yet. Be the first to comment!</p>
    {% endif %}
</div>

{% if request.user.is_authenticated %}
    <!-- Comment Form -->
    <div class="mt-4">
        <h5>Leave a Comment</h5>
        <form action="{% url 'home:post_detail' post.id post.slug %}" method="POST">
            {% csrf_token %}
            {{ comment_form.as_p }}  <!-- Render the ModelForm here -->
            <button type="submit" class="btn btn-primary">Submit</button>
        </form>
    </div>
{% endif %}

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js"></script>
    {% endblock %}
</body>
</html>

home/templates/home/post_edit.html
{% extends 'base.html' %}

{% block title %}Edit Post{% endblock %}

{% block content %}
<div class="container my-4">
    <h2>Edit Post</h2>
    
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        {{ formset.management_form }}
        {% for form in formset %}
            {{ form.as_p }}
        {% endfor %}
        <button type="submit" class="btn btn-primary">Update Post</button>
    </form>
</div>
{% endblock %}