account/urls.py
from django.urls import path
from . import views

app_name = 'account'

urlpatterns = [
    path('account/register', views.UserRegisterationView.as_view(), name='register'),
    path('account/login', views.UserLoginView.as_view(), name='login'),
    path('account/logout', views.UserLogoutView.as_view(), name='logout'),
    path('account/profile/<int:user_id>', views.UserProfileView.as_view(), name='profile'),
    path('account/follow/<int:user_id>', views.UserFollowView.as_view(), name='follow'),
    path('account/unfollow/<int:user_id>', views.UserUnfollowView.as_view(), name='unfollow'),
    path('profile/edit/', views.ProfileEditView.as_view(), name='profile_edit'),

]

home/urls.py
from django.urls import path
from . import views

app_name = 'home'
urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),
    path('post_detail/<int:post_id>/<slug:post_slug>/', views.PostDetailView.as_view(), name='post_detail'),
    path('post_edit/<int:post_id>/', views.PostEditView.as_view(), name='post_edit'),
    path('post_delete/<int:post_id>/', views.PostDeleteView.as_view(), name='post_delete'),
    path('post_create/', views.PostCreateView.as_view(), name='post_create'),
    # path('reply/<int:post_id>/<int:comment_id>/', views.PostAddReplyView.as_view(), name='add_reply'),
    path('post/<int:post_id>/<slug:post_slug>/like/', views.LikePostView.as_view(), name='post_like'),


    ]

twitter/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('', include('account.urls'))
] 
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}My Social Network{% endblock %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet">
</head>
<body>

<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container-fluid">
        <a class="navbar-brand" href="{% url "home:home" %}">Twitter</a>
        <div class="collapse navbar-collapse">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <a class="nav-link" href="{% url "home:home" %}">Home</a>
                </li>
                {% if request.user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url "account:profile" request.user.id %}">Profile</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url "account:logout" %}">Logout</a>
                </li>
                {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url "account:login" %}">Login</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url "account:register" %}">Register</a>
                </li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>

<div class="container">
    {% include "messages.html" %}
    {% block content %}
    {% endblock %}
</div>

</body>
</html>

templates/messages.html
{% if messages %}
    {% for msg in messages %}
        <p class="alert alert-{{ msg.tags }}">{{ msg }}</p>
    {% endfor %}
{% endif %}